Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information
spring:
  cloud:
    discovery:
      registrationMethod: route
eureka:
  instance:
    securePort: 443
    nonSecurePortEnabled: false
    securePortEnabled: true
    healthCheckUrlPath: /health
  client:
    shouldRegisterWithEureka: true
    registerWithEureka: true
    shouldFetchRegistry: true
    fetchRegistry: true
